#server:#  port: 4123

spring:
  datasource:
    url: jdbc:mariadb://election-project-database.cdmnxbm4wkfg.ap-northeast-2.rds.amazonaws.com:3306/election_project_database
    username: hshlego
    password: 970920hshH
    driver-class-name: org.mariadb.jdbc.Driver      jpa:    hibernate:      ddl-auto: none